language: python

python:
  - "2.7"

before_script:
  - psql -c 'create database teste;' -U postgres
  - psql -d teste -f /usr/share/postgresql/9.1/contrib/postgis-1.5/postgis.sql
  - psql -d teste -f /usr/share/postgresql/9.1/contrib/postgis-1.5/spatial_ref_sys.sql 
  - psql -d teste -f /usr/share/postgresql/9.1/contrib/postgis_comments.sql 
  - pip install psycopg2

script:
  - cd src/tests
  - python -m unittest RotaTest
