language: python

python:
  - "2.7"

services:
  - postgresql

env:
  - POSTGIS_VERSION=2

install:
  - sudo apt-get install postgresql-9.1-postgis -q
  - sudo apt-get install tomcat7

before_script:
  - psql -c 'create database teste;' -U postgres
  - psql -d teste -f /usr/share/postgresql/9.1/contrib/postgis-1.5/postgis.sql
  - psql -d teste -f /usr/share/postgresql/9.1/contrib/postgis-1.5/spatial_ref_sys.sql 
  - psql -d teste -f /usr/share/postgresql/9.1/contrib/postgis_comments.sql
  - pip install psycopg2 --use-mirrors
  - pip install unittest-xml-reporting --use-mirrors
  - wget http://sourceforge.net/projects/geoserver/files/GeoServer/2.3.5/geoserver-2.3.5-war.zip
  - sudo unzip geoserver-2.3.5-war.zip /var/lib/tomcat7/webapps/

script:
  - cd src/tests
  - python -m unittest -v runTests

notifications:
  email:
    recipients:
      - matheus1401@gmail.com
    on_success: always
    on_failure: always
