language: python

python:
  - "2.7"

before_script:
  - psql -c 'create database teste;' -U postgres
  - psql -d teste -c 'CREATE EXTENSION postgis;' -U postgres
  - pip install psycopg2

script:
  - cd src/tests
  - python -m unittest RotaTest
