language: python

python:
  - "2.7"

before_script:
  - psql -c 'create database teste;' -U postgres
  - psql -c "create user matheussampaio with unencrypted password 'sampaio';" -U postgres
  - sudo apt-get install python-xmlrunner
  - pip install psycopg2

script:
  - cd src/tests
  - python -m unittest runTests
